### ISSUE TITLE
Completed options return = after the option name on the command line.

### ISSUE THREAD

**Issue by digitalbytes** [ssmith-wustl/Getopt-Complete#3]
When I use this to do completion the command line comes back with an = sign after any option that is configured. 

For example:

  myprogram --tes<TAB>

Returns:

  myprogram --test=

I am wondering if this is the expected behaviour. This seems different than any other shell based completion that I have used in the past.

My config here is OS X Lion perl 5.12.

**Comment by nnutter** [comment]
Hi, I believe it is intended and its purpose is to differentiate between options that require values and boolean switches. I don't know that we intend for it to be different but I don't think I have ever used something that even completes options (only bare arguments like apt-get or subcommands like git). Do you have any examples of option completion?
